[[GnuTLS]]
arch = "aarch64"
git-tree-sha1 = "46d406c391709ee4efe362add28266d926a70840"
os = "macos"

    [[GnuTLS.download]]
    sha256 = "d0baf231f8cd6c610c58d6390cf233b2decde456373e59604323c3e18f8e4589"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.7.8+1/GnuTLS.v3.7.8.aarch64-apple-darwin.tar.gz"
[[GnuTLS]]
arch = "aarch64"
git-tree-sha1 = "580bac78615b52ab78c9b518e6c934582160b7a8"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "fc816554010161938d1b188aae813ac768efe1597beffb16f4600737e6772fe7"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.7.8+1/GnuTLS.v3.7.8.aarch64-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "aarch64"
git-tree-sha1 = "f5a98cf2ba130321c4348d67fe65e91ad6702c87"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "e9164ff396576035cad4bf0637656ed362c4c8094d5bab15886019dd9fcc6441"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.7.8+1/GnuTLS.v3.7.8.aarch64-linux-musl.tar.gz"
[[GnuTLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8f98644e2e1bee1863910bea58065e8a6f3031f6"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "7d9fe7f8a4b7beafc7f24ab4269fe9776c227706bde0a402f9e1aab33af277f1"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.7.8+1/GnuTLS.v3.7.8.armv6l-linux-gnueabihf.tar.gz"
[[GnuTLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dfe1fcb1492d99d38bb3edca8ab38a419dd5319b"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "d1f5c5a444721ae51b56a0e694983cad469139ac4a419d6a936f5af50d564e64"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.7.8+1/GnuTLS.v3.7.8.armv6l-linux-musleabihf.tar.gz"
[[GnuTLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8f98644e2e1bee1863910bea58065e8a6f3031f6"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "7d9fe7f8a4b7beafc7f24ab4269fe9776c227706bde0a402f9e1aab33af277f1"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.7.8+1/GnuTLS.v3.7.8.armv7l-linux-gnueabihf.tar.gz"
[[GnuTLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dfe1fcb1492d99d38bb3edca8ab38a419dd5319b"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "d1f5c5a444721ae51b56a0e694983cad469139ac4a419d6a936f5af50d564e64"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.7.8+1/GnuTLS.v3.7.8.armv7l-linux-musleabihf.tar.gz"
[[GnuTLS]]
arch = "i686"
git-tree-sha1 = "6a503a93f0d0e4373e4e37f19cfcb9a309a6773b"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "2b72dfbd7cf4cdaec8a523f536c7212ad600db1fc615c663f359475f4fa4b978"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.7.8+1/GnuTLS.v3.7.8.i686-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "i686"
git-tree-sha1 = "fb63634e2fc42ac20f4cb3195d2c5976f69ba36b"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "a76fe49e4d56ec34222c5f1b111b081f5b542d75eff5f64c9687eb9ceca798ce"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.7.8+1/GnuTLS.v3.7.8.i686-linux-musl.tar.gz"
[[GnuTLS]]
arch = "powerpc64le"
git-tree-sha1 = "89295ec508c2979dc77458877f48b0ba1c109342"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "b1b4aa0da4788cd24c27285678cef6c7f559736f06685209198f9f526000dc38"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.7.8+1/GnuTLS.v3.7.8.powerpc64le-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "x86_64"
git-tree-sha1 = "e9b5a09438942c0d1fde426ffcece33d5c1f45c0"
os = "macos"

    [[GnuTLS.download]]
    sha256 = "d4737c9f962e4b266a14855eef5427a9862c0c9c2f4bb3db45bac077d05d2cf0"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.7.8+1/GnuTLS.v3.7.8.x86_64-apple-darwin.tar.gz"
[[GnuTLS]]
arch = "x86_64"
git-tree-sha1 = "8e68058ee1bcce8b23816044b73dd9f9f2d870b7"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "a343a49648006bf7c34f634d880e6b42918bfc85d6bafafbd0f232bad1ccc359"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.7.8+1/GnuTLS.v3.7.8.x86_64-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "x86_64"
git-tree-sha1 = "345b107ad841ea6d069ab46400610adfbeab5f9f"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "ade72d20105953eb9cec01f523f3dc8b40fbe6a102811100420506aafd19ac1b"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.7.8+1/GnuTLS.v3.7.8.x86_64-linux-musl.tar.gz"
[[GnuTLS]]
arch = "x86_64"
git-tree-sha1 = "5e794dabb70ba8eb0ffd5cd49f537e6ef6b6103b"
os = "freebsd"

    [[GnuTLS.download]]
    sha256 = "6592dd5859163d2b9a372211493cc61328dc6db86fe957466b34296efc1d3f96"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.7.8+1/GnuTLS.v3.7.8.x86_64-unknown-freebsd.tar.gz"
