[[GnuTLS]]
arch = "aarch64"
git-tree-sha1 = "7850fded89b3fee8a13a87ee2c8828e4c0063222"
os = "macos"

    [[GnuTLS.download]]
    sha256 = "ae6a8aba62cb57b035bd7a291040a11983ce2fa2bab66a747965c7be29a4eac7"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.4+0/GnuTLS.v3.8.4.aarch64-apple-darwin.tar.gz"
[[GnuTLS]]
arch = "aarch64"
git-tree-sha1 = "3fd09d3a6782f93f8e944bbcbeb7f5ff56203c43"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "1fad190639c8691f7855ce859bde5f54b78a5a604d592d8eddfe6f9734c370e6"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.4+0/GnuTLS.v3.8.4.aarch64-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "aarch64"
git-tree-sha1 = "6c7d839fc1c4e79364a9c89cafdf7604c5c44ddb"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "2c8620c3d9ac85667b8328b8fef0861c467d419b1556b755768dc32b8585ea8a"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.4+0/GnuTLS.v3.8.4.aarch64-linux-musl.tar.gz"
[[GnuTLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0ab752e6c325521b44bddddd9859336d79be14ca"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "d090c933f7a9661cf82d29b8ce622854e54fdae9add3c863c52b573288cfc8fb"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.4+0/GnuTLS.v3.8.4.armv6l-linux-gnueabihf.tar.gz"
[[GnuTLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a007886b410d1a05b23d9b33ba67a28d3c4103fe"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "395dd941b3fbb1cbd65722a4be987f99dc501e3b4920e55ed0f6e62e97f163f2"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.4+0/GnuTLS.v3.8.4.armv6l-linux-musleabihf.tar.gz"
[[GnuTLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0ab752e6c325521b44bddddd9859336d79be14ca"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "d090c933f7a9661cf82d29b8ce622854e54fdae9add3c863c52b573288cfc8fb"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.4+0/GnuTLS.v3.8.4.armv7l-linux-gnueabihf.tar.gz"
[[GnuTLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a007886b410d1a05b23d9b33ba67a28d3c4103fe"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "395dd941b3fbb1cbd65722a4be987f99dc501e3b4920e55ed0f6e62e97f163f2"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.4+0/GnuTLS.v3.8.4.armv7l-linux-musleabihf.tar.gz"
[[GnuTLS]]
arch = "i686"
git-tree-sha1 = "b8fbd54c39d4a5872e73657f6d620c92703e7880"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "15179289babaee2e6854e15ef8e5a854b635079dd9a3c540f50772fe7275c2fb"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.4+0/GnuTLS.v3.8.4.i686-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "i686"
git-tree-sha1 = "0c2a79a85576be1eb3ec7bc78608a5142c091592"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "cf1aca41ce5efd0a80a73176e32be89720454b5f0b6a85ec53381072d0d58b46"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.4+0/GnuTLS.v3.8.4.i686-linux-musl.tar.gz"
[[GnuTLS]]
arch = "powerpc64le"
git-tree-sha1 = "e2f8b3c215d42a1826d9db92c2b0bd7586968b54"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "31db85b20ac23d5f0a474487d9653b9e57a5acdc32e3381facaee7707484785c"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.4+0/GnuTLS.v3.8.4.powerpc64le-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "x86_64"
git-tree-sha1 = "db18e947117c74679c744e65f2e3d2e96711815d"
os = "macos"

    [[GnuTLS.download]]
    sha256 = "57ad257fe127688dd3210559d8dd1554bfc56d28b215ec642834184a249453c5"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.4+0/GnuTLS.v3.8.4.x86_64-apple-darwin.tar.gz"
[[GnuTLS]]
arch = "x86_64"
git-tree-sha1 = "61ede290974284fcbb9ff32a72f6dec42be6bd0c"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "7efdf842edba2db24696fc92e3f07800f122db918a45dfc1c4ea7ef38f14b39a"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.4+0/GnuTLS.v3.8.4.x86_64-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "x86_64"
git-tree-sha1 = "58a89a7ce7b67e656b7c985e8dc6b0c53d2f021e"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "e05ec8d53b1b4afc1c51f6744de93adc8577787baf4e081a7be7bf1b9e3561c5"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.4+0/GnuTLS.v3.8.4.x86_64-linux-musl.tar.gz"
[[GnuTLS]]
arch = "x86_64"
git-tree-sha1 = "b280cfdda2eee00fe51db4487a6e96ef70fd0c84"
os = "freebsd"

    [[GnuTLS.download]]
    sha256 = "bf1bc4670b78d79779905cd4e23bc2613163a79ed3fd2bfe50b785fbbafdb4ec"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.4+0/GnuTLS.v3.8.4.x86_64-unknown-freebsd.tar.gz"
