[[GnuTLS]]
arch = "x86_64"
git-tree-sha1 = "c47e9a09e28175e3fc1b8a1134b2f2a50887f00d"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "a9dc9020cce74bd2f715a9cb503da3aa0099972f3345c059cd37a9edbfe253d7"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.6.13+0/GnuTLS.v3.6.13.x86_64-linux-musl.tar.gz"
[[GnuTLS]]
arch = "powerpc64le"
git-tree-sha1 = "f8e1e0e527ea2ecc0e38323b5f171e385322722f"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "6efa8e5eac9f49db2d20a2e8c27f6b73ad59b1febdf2b719c7627e67e5c7b1e2"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.6.13+0/GnuTLS.v3.6.13.powerpc64le-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "x86_64"
git-tree-sha1 = "062fc6f49ad561d436dd72c987e69a7077484f0a"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "3102f2340121e6b5e05dc0a85dd4c8af9d0681cddfd443ba1cf2a04fae29ec7d"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.6.13+0/GnuTLS.v3.6.13.x86_64-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "armv7l"
git-tree-sha1 = "34f052811d68b30a66307861a751872571d8c4ac"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "c6bec8d8c644e97f2ca6287a8d240124dadf16373bbd177b080243729368a89d"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.6.13+0/GnuTLS.v3.6.13.armv7l-linux-gnueabihf.tar.gz"
[[GnuTLS]]
arch = "aarch64"
git-tree-sha1 = "3df2852a2e4a84ea0ca79d859a896aca54e56b52"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "2b13ee0d50c89c917d2edcd02f23a99501b9dfd37b629282d91f6f29fdc918f9"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.6.13+0/GnuTLS.v3.6.13.aarch64-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "armv7l"
git-tree-sha1 = "1a00b0f2c42608d03423ccdc598af816d6b0a027"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "66a62e9d1fc0e15aba1abe7fc99ec1687a952d88d87e9c1550b6530a7cac83eb"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.6.13+0/GnuTLS.v3.6.13.armv7l-linux-musleabihf.tar.gz"
[[GnuTLS]]
arch = "i686"
git-tree-sha1 = "627de275adc86f2c08a0f8f815519044d1898fd7"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "32e9465e6c9943eb0d4dd03ef0eb412603a8cd677ffa21cfc52335f74a39bde2"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.6.13+0/GnuTLS.v3.6.13.i686-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "x86_64"
git-tree-sha1 = "8360652a6e108eda2e87df962de45cf1153ec550"
os = "macos"

    [[GnuTLS.download]]
    sha256 = "4d1a7785964c8bc049a54b1072d2c8bc2e6ada3d2f6d8813b19c4dea9a70bc7a"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.6.13+0/GnuTLS.v3.6.13.x86_64-apple-darwin14.tar.gz"
[[GnuTLS]]
arch = "i686"
git-tree-sha1 = "695e2ca803ef5065782e1c6f38608d8a2f4dbb5c"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "fa06f6f5b5916f4c5abf8bf324b4620dad0d238001951c16b5a547c3d4304935"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.6.13+0/GnuTLS.v3.6.13.i686-linux-musl.tar.gz"
[[GnuTLS]]
arch = "aarch64"
git-tree-sha1 = "9eaefa0e5eb5d3b9b3ec07850e5de4518dd41ad2"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "84780e3205c97eb83aa1367cd38c01760496dc06d9ff0d9e9bbfe54d3022e416"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.6.13+0/GnuTLS.v3.6.13.aarch64-linux-musl.tar.gz"
