[[GnuTLS]]
arch = "aarch64"
git-tree-sha1 = "c67eef60aaed1a766b5ce608541a3acd31a03cd0"
os = "macos"

    [[GnuTLS.download]]
    sha256 = "4732760282d2adb620bb10a324c68ed620980f30d0a7f71b2a569cdd57de18ac"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.3+0/GnuTLS.v3.8.3.aarch64-apple-darwin.tar.gz"
[[GnuTLS]]
arch = "aarch64"
git-tree-sha1 = "b3c95bf95d6215d7fc03c102eb778eb748b46ed7"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "b18ca9472b9998c6dd0510a0b4f8debad3f9472f67a37375a612f75c24bd9b4d"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.3+0/GnuTLS.v3.8.3.aarch64-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "aarch64"
git-tree-sha1 = "94d22af3827bfee797c3b07f5c4f6bf1594281d6"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "9129aba30f6cf5561f802e973001fc42e300564215b3355479b2ec064c49e8b4"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.3+0/GnuTLS.v3.8.3.aarch64-linux-musl.tar.gz"
[[GnuTLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "59560d284957aa1a97af41985b0686ad1446e6dc"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "77cba750607a3e40cf3cf0d112ba87e5735405957ab99f04e9911b0cc4858b55"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.3+0/GnuTLS.v3.8.3.armv6l-linux-gnueabihf.tar.gz"
[[GnuTLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5d0886f6acd2d6ef0684b5a758f68f73e8730a2f"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "deeebd2959632474466f40477a5d150e297be0605b24e5d77df9c53fc32e1d81"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.3+0/GnuTLS.v3.8.3.armv6l-linux-musleabihf.tar.gz"
[[GnuTLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "59560d284957aa1a97af41985b0686ad1446e6dc"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "77cba750607a3e40cf3cf0d112ba87e5735405957ab99f04e9911b0cc4858b55"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.3+0/GnuTLS.v3.8.3.armv7l-linux-gnueabihf.tar.gz"
[[GnuTLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5d0886f6acd2d6ef0684b5a758f68f73e8730a2f"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "deeebd2959632474466f40477a5d150e297be0605b24e5d77df9c53fc32e1d81"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.3+0/GnuTLS.v3.8.3.armv7l-linux-musleabihf.tar.gz"
[[GnuTLS]]
arch = "i686"
git-tree-sha1 = "3522a022abfc9f393307b7a3da7cbd8e3cf20588"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "28a6d5551d5a8db72135fd6f4f041f1f0fe522374eb03a21c49aa6f3abd47848"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.3+0/GnuTLS.v3.8.3.i686-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "i686"
git-tree-sha1 = "cc0116842fb61335a2fdd0cf787a2b232507febb"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "a49f4e8d2af13efc6834fe26414919afe575983cb37e2ac40463861ccea860e4"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.3+0/GnuTLS.v3.8.3.i686-linux-musl.tar.gz"
[[GnuTLS]]
arch = "powerpc64le"
git-tree-sha1 = "d9235ba568e7b1176358904f154f1d5f2f50c904"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "a9c9f8a86d8a08d0ec3370a87fcd3fe74a11c45654004c99c8373e6afc174a02"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.3+0/GnuTLS.v3.8.3.powerpc64le-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "x86_64"
git-tree-sha1 = "c33444824b6fdfac33e5fddf73b139211a8bfe72"
os = "macos"

    [[GnuTLS.download]]
    sha256 = "faddf19f9856f74d3ecf6c8fb2f391ebd6cd91d6b5fe97c7f830b5d0dc960124"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.3+0/GnuTLS.v3.8.3.x86_64-apple-darwin.tar.gz"
[[GnuTLS]]
arch = "x86_64"
git-tree-sha1 = "922cfdff923e16c9a8208f5b5ab852d00e8bf193"
libc = "glibc"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "cd57e3b0d0b1cf51ef6d9bcef65e06e97193626ae11a017f3741acb2fbd2c1af"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.3+0/GnuTLS.v3.8.3.x86_64-linux-gnu.tar.gz"
[[GnuTLS]]
arch = "x86_64"
git-tree-sha1 = "a0971a07a10eaed3ad3a466d422ca28cade4a22a"
libc = "musl"
os = "linux"

    [[GnuTLS.download]]
    sha256 = "b71df49ea7148af47d0c512d7f0eec6560f3dccf0415fcb0c8f09db25d7f60d7"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.3+0/GnuTLS.v3.8.3.x86_64-linux-musl.tar.gz"
[[GnuTLS]]
arch = "x86_64"
git-tree-sha1 = "b6c5097fac77b60fc94cba88788316f31d1d63d6"
os = "freebsd"

    [[GnuTLS.download]]
    sha256 = "7194ec7578bb18e6cde17d665be17a4e703097e6dd07395ba77c5c2e04eb9ff6"
    url = "https://github.com/JuliaBinaryWrappers/GnuTLS_jll.jl/releases/download/GnuTLS-v3.8.3+0/GnuTLS.v3.8.3.x86_64-unknown-freebsd.tar.gz"
